version: '3'

services:
  photomaster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photomaster_app
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - photomaster_network

  mysql:
    image: mysql:8.0
    container_name: photomaster_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photomaster
      MYSQL_USER: photomaster
      MYSQL_PASSWORD: photomaster
    ports:
      - "3307:3306"  # Changed port to avoid XAMPP conflict
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - photomaster_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: photomaster_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - photomaster_network

networks:
  photomaster_network:
    driver: bridge

volumes:
  mysql_data:
