version: '3'

services:
  # Laravel Backend
  laravel:
    build:
      context: ./laravel
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=photomaster
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - photomaster-network
    command: bash -c "php artisan config:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0"

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"  # Changed port to avoid conflict with XAMPP
    environment:
      - MYSQL_DATABASE=photomaster
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - photomaster-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - photomaster-network

  # React Frontend
  react:
    build:
      context: ./electron-react
    ports:
      - "3000:3000"
    volumes:
      - ./electron-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - laravel
    networks:
      - photomaster-network

networks:
  photomaster-network:
    driver: bridge

volumes:
  mysql_data:
