version: '3'

services:
  # Laravel Backend
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount specific directories but exclude the problematic ones
      - ./laravel/app:/var/www/html/app
      - ./laravel/bootstrap:/var/www/html/bootstrap
      - ./laravel/config:/var/www/html/config
      - ./laravel/database:/var/www/html/database
      - ./laravel/resources:/var/www/html/resources
      - ./laravel/routes:/var/www/html/routes
      - ./laravel/tests:/var/www/html/tests
      - ./laravel/.env:/var/www/html/.env
      - ./laravel/artisan:/var/www/html/artisan
      - ./laravel/composer.json:/var/www/html/composer.json
      - ./laravel/composer.lock:/var/www/html/composer.lock
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=photomaster
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - photomaster-network
    command: bash -c "php artisan config:clear && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0"

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=photomaster
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - photomaster-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - photomaster-network

  # React Frontend
  react:
    build:
      context: ./electron-react
    ports:
      - "3000:3000"
    volumes:
      - ./electron-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - laravel
    networks:
      - photomaster-network

networks:
  photomaster-network:
    driver: bridge

volumes:
  mysql_data:
